[package]
name = "ai_vault_tp_v526"
version = "0.0.1"

[addresses]
# Address will be replaced on deployment
ai_vault_tp_v526 = "0x4eaa8579acdc8819a1c2775c2e05145399841c652701b303ea41c1793dce01ee"
liquidswap_v05 = "0x0163df34fccbf003ce219d3f1d9e70d140b60622cb9dd47599c25fb2f797ba6e"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "aptos-framework-v1.24.1" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "aptos-framework-v1.24.1" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "aptos-framework-v1.24.1" }
Liquidswapv05 = { git = "https://github.com/pontem-network/liquidswap_v05.git", rev = "v0.5.0" }
